[package]
name = "account-set"
version = "0.4.0"
authors = ["Gautam Dhameja <quasijatt@outlook.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/gautamdhameja/substrate-account-set"

[features]
default = ['std']
std = [
    'codec/std',
    'sp-std/std',
    'sp-runtime/std',
    'frame-support/std',
    'sp-core/std',
    'sp-io/std',
    'frame-system/std',
    'serde',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
serde = { features = ['derive'], optional = true, version = '1.0.101' }
sp-std = { default-features = false, version = '2.0.0', path = "../../../../primitives/std"}
sp-runtime = { default-features = false, version = '2.0.0', path = "../../../../primitives/runtime" }
sp-core = { default-features = false, version = '2.0.0', path = "../../../../primitives/core" }
frame-support = { default-features = false, version = '2.0.0', path = "../../../../frame/support" }
frame-system = { default-features = false, version = '2.0.0', path = "../../../../frame/system" }
sp-io = { default-features = false, version = '2.0.0', path = "../../../../primitives/io" }
